# Generated by Django 2.0 on 2017-12-19 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ttype', models.CharField(choices=[('income', 'income'), ('expense', 'expense')], db_index=True, default='expense', max_length=16, verbose_name='Type')),
                ('name', models.CharField(db_index=True, max_length=32, verbose_name='Name')),
                ('date', models.DateField(blank=True, db_index=True, default=datetime.datetime.now, null=True, verbose_name='Date')),
                ('amount', models.IntegerField(default=0, verbose_name='Amount')),
                ('lastedited', models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='Last editing Date')),
                ('addeddate', models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='Date Added on')),
                ('comments', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='Other')),
            ],
        ),
        migrations.CreateModel(
            name='Total',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='A', max_length=16, verbose_name='Name')),
                ('totalamount', models.IntegerField(default=0, verbose_name='Funds left')),
                ('tincome', models.IntegerField(default=0, verbose_name='Total Earned')),
                ('texpense', models.IntegerField(default=0, verbose_name='Total Spent')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='info',
            unique_together={('name', 'date', 'amount')},
        ),
    ]
