# Generated by Django 2.0 on 2017-12-19 11:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='comments',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Other'),
        ),
        migrations.AlterField(
            model_name='info',
            name='date',
            field=models.DateField(blank=True, db_index=True, default=datetime.datetime.now, verbose_name='Date'),
        ),
        migrations.AlterUniqueTogether(
            name='info',
            unique_together={('name', 'date', 'amount')},
        ),
    ]
