# Generated by Django 2.0 on 2017-12-19 11:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20171219_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='addeddate',
            field=models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='Date Added on'),
        ),
        migrations.AlterField(
            model_name='info',
            name='comments',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='Other'),
        ),
        migrations.AlterField(
            model_name='info',
            name='lastedited',
            field=models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='Last editing Date'),
        ),
    ]
