# Generated by Django 2.0 on 2017-12-19 11:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20171219_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='date',
            field=models.DateField(blank=True, db_index=True, default=datetime.datetime.now, null=True, verbose_name='Date'),
        ),
    ]
